### ISSUE TITLE
Pattern file

### ISSUE THREAD

**Issue by AbraamSa** [renzilin/NanoForenSTR#3]
is any way to make NanoForenSTR read more than one pattern for same locus 
for example FGA pattern is [GGAA]n [GGAG]n [AAAG]n [AGAA]n [AAAA]n [GAAA]n and in PAT file you used AGAA as pattern format which miss the actual allele number in most cases

**Comment by renzilin** [comment]
Hi AbraamSa,

In current version, we use fuzzy search on repeat motif. And we're developing a new upcoming version where all repeat motif are counted in and more loci can be genotyped robustly. However, the locus FGA isn't included. I think it might be due to the homopolymer problem in nanopore sequencing. And our tools for both versions can't handle FGA, PentaD, and PentaE very well.

Zilin RenPhD student at BRIM
***@***.*** ***@***.***)
+8613269333608 (tel:+8613269333608)

**Comment by AbraamSa** [comment]
thank you for your reply, i hope if you can give me fastq data for 2800M samples as i can't get them

**Comment by renzilin** [comment]
Sure, please send me your email address. Cuz we have the network issue

**Comment by AbraamSa** [comment]
Thank you, here are both mails you can send on it.
abraamsamir14@gmail.com
abraams@hitstechnology.com
